# -*- coding: utf-8 -*-
"""block_matrix_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8Itqibv_GiLdMhPZBA-Rl8vGbmL8opJ
"""

import numpy as np

from matlib_z3342_tem1_msgvk.dense import FullMatrix
from matlib_z3342_tem1_msgvk.block import BlockMatrix


def main():
    A11 = FullMatrix(
        np.array([
            [1, 2],
            [3, 4]
        ])
    )

    A12 = FullMatrix(
        np.array([
            [5, 6],
            [7, 8]
        ])
    )

    A21 = FullMatrix(
        np.array([
            [9, 10],
            [11, 12]
        ])
    )

    A22 = FullMatrix(
        np.array([
            [13, 14],
            [15, 16]
        ])
    )

    B = BlockMatrix([
        [A11, A12],
        [A21, A22]
    ])

    print("Block matrix:")
    print(B)

    print("\nShape:")
    print(B.shape)

    print("\nDense representation:")
    print(B.to_dense())

    x = np.array([1, 1, 1, 1])

    print("\nMatrix-vector product:")
    print(B.matvec(x))


if __name__ == "__main__":
    main()