# -*- coding: utf-8 -*-
"""poisson_1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8Itqibv_GiLdMhPZBA-Rl8vGbmL8opJ
"""

import numpy as np

from matlib_z3342_tem1_msgvk import FullMatrix
from matlib_z3342_tem1_msgvk.solvers import solve


def build_poisson_matrix(n):
    A = FullMatrix.zero(n, n, 0.0)

    for i in range(n):
        A[i, i] = 2.0

        if i > 0:
            A[i, i - 1] = -1.0

        if i < n - 1:
            A[i, i + 1] = -1.0

    return A


def main():
    n = 10

    A = build_poisson_matrix(n)

    h = 1.0 / (n + 1)

    b = np.ones(n) * h**2

    u = solve(A, b)

    print("Poisson matrix:")
    print(A.to_dense())

    print("\nRight-hand side:")
    print(b)

    print("\nSolution:")
    print(u)


if __name__ == "__main__":
    main()